name: "Integration Tests"

on:
  pull_request:
    branches: [ master ]

jobs:
  integration_tests:
    if: |
      github.head_ref == 'autonity' ||
      github.head_ref == 'autonity-demo' ||
      github.head_ref == 'autonity-network'

    runs-on: ubuntu-20.04

    steps:
    - name: git checkout
      uses: actions/checkout@v2

    - name: Set useful variables
      run: |
        echo "CHART_PATH=stable/$GITHUB_HEAD_REF" >> $GITHUB_ENV
        echo "ACTOR_LOWERCASE=$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
        echo "SHORT_SHA=$(echo $GITHUB_SHA|head -c 7)" >> $GITHUB_ENV

    - name: Get useful variables
      run: |
        echo 'Chart path: '$CHART_PATH
        echo 'Actor: '$GITHUB_ACTOR
        echo 'Actor Lowercase: '$ACTOR_LOWERCASE
        echo 'Short SHA: '$SHORT_SHA
        echo 'GitHub Run ID: '$GITHUB_RUN_ID

    - name: Install Kind & Create cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: v0.11.1
        name: local-cluster
        wait: 60s
        skipClusterCreation: false
    
    - name: Test Kind cluster creation
      run: kind get clusters

    - name: Install helm
      uses: azure/setup-helm@v1
      with:
        version: '3.2.4'
      id: install

    - name: Add the external Helm chart repositories
      run: |
        helm repo add stable https://charts.helm.sh/stable
        helm repo add charts-ose.clearmatics.com https://charts-ose.clearmatics.com

    - name: List the active repositories and update the dependencies
      run: |
        helm repo list
        helm dependency update $CHART_PATH

    - name: Deploy the chart
      run: |
        kubectl create namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID
        helm install $GITHUB_HEAD_REF-$SHORT_SHA $CHART_PATH --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID
        # Sadly --wait fails, so have to sleep, look to maybe pull in mock test to solve
        # this problem another way
        sleep 120

    - name: Run the tests
      run: helm test $GITHUB_HEAD_REF-$SHORT_SHA --namespace $ACTOR_LOWERCASE-$GITHUB_RUN_ID
